config/routes.rb
HackerNewsClone::Application.routes.draw do
  resources :users
  resources :posts
  resources :save_stories
  resources :comments
  resources :comment_votes
  resource :session
  resources :post_votes

  root :to => 'posts#index'

  match '/comment_upvote', to: 'comment_votes#create'
  match '/login',    to: 'sessions#new'
  match '/logout',   to: 'sessions#destroy'
  match '/register', to: 'users#new'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :parent_id, :post_id, :author_id, :body

  belongs_to :post
  belongs_to :parent, :class_name => 'Comment'
  belongs_to :author, :class_name => 'User'

  has_many :comment_votes
  has_many :users, :through => :comment_votes
end

app/models/comment_vote.rb
class CommentVote < ActiveRecord::Base
  attr_accessible :user_id, :comment_id

  belongs_to :user
  belongs_to :post
  # attr_accessible :title, :body
end

app/models/email.rb
class Email < ActiveRecord::Base
  attr_accessible :email_address

  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :author_id, :body, :link, :parent_id, :title

  belongs_to :author, :class_name => 'User'
  belongs_to :parent, :class_name => 'Post'

  has_many :comments
  has_many :post_votes
  has_many :users, :through => :post_votes
end

app/models/post_vote.rb
class PostVote < ActiveRecord::Base
  attr_accessible :user_id, :post_id

  belongs_to :user
  belongs_to :post
  # attr_accessible :title, :body
end

app/models/save_story.rb
class SaveStory < ActiveRecord::Base
  attr_accessible :user_id, :post_id

  belongs_to :user
  belongs_to :post
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :about, :delay, :email, :max_visit, :min_away,
                  :no_procast, :password_digest, :show_dead, :username,
                  :emails_attributes

  has_many :emails
  accepts_nested_attributes_for :emails, :reject_if => :all_blank

  has_many :comment_votes
  has_many :post_votes
  has_many :posts
  has_many :comments
  has_many :save_stories

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/comment_votes_controller.rb
class CommentVotesController < ApplicationController
  def new
  end
  def create
    if CommentVote.where("comment_id = ? AND user_id = ?", params[:comment_id],
                                                       current_user.id).empty?
      CommentVote.create(:comment_id => params[:comment_id],
                     :user_id => current_user.id)
    end
    redirect_to :back
  end
end

# REV: Nice.  I like the way you structured this. 

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(params[:comment])
    @comment.author_id = current_user.id
    if @comment.save
      redirect_to comment_path(@comment)
    else
      render :new
    end
  end

  def show
    @current_comment = Comment.includes(:author).find(params[:id])
    @comment = Comment.new
    #@comments = add stuff to find children # REV: ... 
    @comments = Comment.where(:post_id => @current_comment.post_id)
  end
end

# REV: I agree that comments should not be able to be edited.  

app/controllers/post_votes_controller.rb
class PostVotesController < ApplicationController
  def create
    if PostVote.where("post_id = ? AND user_id = ?", params[:post_id],
                                                       current_user.id).empty?
      PostVote.create(:post_id => params[:post_id],
                     :user_id => current_user.id)
    end
    redirect_to :back
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:author)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    @post.author_id = current_user.id
    #params[:id]
    @post.body = nil unless @post.link.empty?
    if @post.save
      redirect_to post_url(@post)
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @post = Post.find(params[:id])
    @comments = Comment.where(:post_id => @post.id).includes(:author)
  end


end

# REV: Are users able to destroy posts? 

app/controllers/save_stories_controller.rb
class SaveStoriesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @username = "" 
  end

  def create
    if login(params[:username], params[:password])
      redirect_to root_url
    else
      @username = params[:username]
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url
  end
end


# REV: Looks great!

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    3.times { @user.emails.build }
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      login(params[:user][:username], params[:user][:password])
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to edit_user_url(@user)
    else
      render :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_votes_helper.rb
module CommentVotesHelper
  def comment_karma(comment)

  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_count(post_id)
    Comment.where(:post_id => post_id).count
  end
end

app/helpers/post_votes_helper.rb
module PostVotesHelper
  def total_post_karma(post_id)
    PostVote.where(:post_id => post_id).count
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/save_stories_helper.rb
module SaveStoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(username, password)
    user = User.find_by_username(username)

    if !user.nil? && user.authenticate(password)
      #if user.remember_token.nil?
      user.remember_token = SecureRandom.hex(16)
      session[:remember_token] = user.remember_token
      p session
      user.save!
      true
    else
      #end
      false
    end
  end
  def current_user
    p session
    p "SESSION TOKEN LALALA: #{session[:remember_token]}"
    return nil if session[:remember_token].nil?
    @user ||= User.find_by_remember_token(session[:remember_token])
  end

  def logout
    raise "Should not be logging out"
    current_user.remember_token = nil
    current_user.save!
    session[:remember_token] = nil
  end

  def logged_in?
    not current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_display.html.erb
<%= link_to "^", {:controller => :comment_votes, :action => :create, :comment_id => comment.id }, :method => :post %>
<small>
  <%=link_to "#{comment.author.username}", user_path(comment.author_id)%>
  TIME STAMP STUFF |
  <%=link_to "link", comment_path(comment)%>
  <% if show_parent && !comment.parent_id.nil?%>
   <%= " | " %><%= link_to "parent", comment_path(comment.parent_id) %>
  <% end %>
</small>
<br>
<%= comment.body %>
<br>
<small>
  <%= link_to "reply", comment_path(comment)%>
</small>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <%= f.hidden_field :post_id, :value => "#{post_id}" %>
  <%= f.hidden_field :parent_id, :value => "#{parent_id}" %>
  <%=f.text_area :body %>
  <br>
  <%=f.submit "Reply" %>
<% end %>

app/views/comments/show.html.erb
<p>

  <%= render :partial => 'comments/display', :locals => {:comment => @current_comment, :show_parent => true }%>
</p>

<p>
  <%= render :partial => 'comments/form', :locals => {:parent_id => @current_comment.id, :post_id => @current_comment.post_id }%>
</p>

<p>
  <% @comments.each do |comment| %>
  <%= render :partial => 'comments/display', :locals => {:comment => comment, :show_parent => false} %>
  <br><br>
  <% end %>
</p>

app/views/posts/index.html.erb
<ol>
  <% @posts.each do |post| %>
  <li>
    <%= link_to "^", {:controller => :post_votes, :action => :create, :post_id => post.id }, :method => :post %>
    <% if post.link.empty?%>
      <%= link_to post.title, post_url(post) %>
    <% else %>
      <a href="<%= "http://#{post.link}" %>"><%= post.title %></a>
    <% end%>
    <small>
      <%= post.link.empty? ? nil : "(#{post.link})" %>
    </small>
    <br>
    <%=total_post_karma(post.id)%> points by <%= link_to post.author.username, user_url(post.author)%> |
    <%="#{distance_of_time_in_words_to_now(post.created_at)} ago" %> |
    <%= link_to "#{comment_count(post.id)} Comments", post_path(post) %>
  </li>
  <% end %>
</ol>

app/views/posts/new.html.erb
<h1>Submit</h1>
<%= form_for(@post) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :link %>
  <%= f.text_field :link %>
  <br>
  <b>or</b>
  <br>
  <%= f.label :body %>
  <br>
  <%= f.text_area :body %>
  <br>
  <%#= f.fields_for(:comments) do |comment_form| %>

    <%#= comment_form.label :body, "First Comment:"%>
    <%#= comment_form.text_area :body %>
    <br>
  <%# end %>

  <br>
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<p>
  <% if @post.link.empty?%>
    <%= link_to @post.title, post_url(@post) %>
  <% else %>
    <a href="http://<%= "#{@post.link}" %>"><%= @post.title %></a>
  <% end%>
  <small>
    <%= @post.link.empty? ? nil : "(#{@post.link})" %>
  </small>
  <br>
  <small>
   <%=total_post_karma(@post.id)%> points by <%= link_to @post.author.username, user_url(@post.author)%> |
    <%="#{distance_of_time_in_words_to_now(@post.created_at)} ago" %> |
  <%= link_to "#{comment_count(@post.id)} Comments", post_path(@post) %>
  </small>
</p>

<p>
  <%= @post.body %>
</p>

<p>
  <%= render :partial => 'comments/form', :locals => {:parent_id => nil, :post_id => @post.id }%>
</p>

<p>
  <% @comments.each do |comment| %>
  <%= render :partial => 'comments/display', :locals => {:comment => comment, :show_parent => false} %>
  <br><br>
  <% end %>
</p>

app/views/users/new.html.erb
<h1>Create Account</h1>
<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>

  <%= f.fields_for(:emails) do |email_form| %>

    <%= email_form.label :email_address, "Email:"%>
    <%= email_form.text_field :email_address %>
    <br>
  <% end %>
  <%= f.submit %>
<% end %>